DROP TABLE audit_logs CASCADE;
DROP TABLE restrains CASCADE;
DROP TABLE message_mentions CASCADE;
DROP TABLE messages CASCADE;
DROP TABLE dm_channel_users CASCADE;
DROP TABLE dm_channels CASCADE;
DROP TABLE room_channels CASCADE;
DROP TABLE channels CASCADE;
DROP TABLE emotes CASCADE;
DROP TABLE roles CASCADE;
DROP TABLE user_roles CASCADE;
DROP TABLE videos CASCADE;
DROP TABLE subtitles CASCADE;
DROP TABLE rooms CASCADE;
DROP TABLE users CASCADE;
DROP TABLE files CASCADE;


DROP EXTENSION IF EXISTS "uuid-ossp";
DROP SEQUENCE IF EXISTS global_id_sequence;
